app = "carbonable-event-indexer-sepolia"
primary_region = 'cdg'

[build]
build-target = "production"

[env]
NETWORK = "sepolia"

[processes]
indexer = "./indexer"


[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ['indexer']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
